# Generated by Django 6.0.1 on 2026-02-18 16:48

import django_validated_jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_info',
            field=django_validated_jsonfield.fields.ValidatedJSONField(default=None),
        ),
    ]
