# Generated by Django 6.0.1 on 2026-02-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
