# Generated by Django 6.0.1 on 2026-03-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Selom Amuzu', max_length=60),
            preserve_default=False,
        ),
    ]
