# Generated by Django 6.0.1 on 2026-03-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_progress_lesson_unique_lesson_per_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
